services:
  web:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    command:
      [
        "/bin/bash",
        "-c",
        "chmod +x ./scripts/init-db.sh && ./scripts/init-db.sh 2>&1 | tee /app/init-db.log && bun run nodemon --watch app/db/pg/schema --watch app/db/pg/[...api] --watch db.json --ext ts,json --exec 'bun run db:migrate-seed' & bun run dev",
      ]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app_db
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: [node_modules, .github]
        - action: rebuild
          path: package.json
    volumes:
      - postgres_data:/app/data

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build:
      context: .
      target: test
    profiles:
      - test
    command: ["bun", "run", "test"]
    depends_on:
      web:
        condition: service_healthy
    environment:
      - ENV=docker

  test-pg:
    build:
      context: .
      target: test
    profiles:
      - test
    command: ["bash", "-c", "chmod +x ./scripts/run-test.sh && ./scripts/run-test.sh"]
    volumes:
      - .:/app
    depends_on:
      web:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - ENV=docker
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/app_db

volumes:
  postgres_data:
    driver: local
