services:
  web:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    command: ["bun", "run", "dev"]
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
