services:
  web:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    command: ["bun", "run", "dev"]
    develop:
      watch:
        - action: sync
          path: .
          ignore: [node_modules, .github]
        - action: rebuild
          path: package.json

  test:
    build:
      context: .
      target: test
    profiles:
      - test
    command: ["bun", "test"]
    depends_on:
      web:
        condition: service_healthy
