name: Test

on:
  push:
    paths-ignore:
      - README.md
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: docker compose --profile test up --abort-on-container-exit --exit-code-from test

      - name: Notify Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: message,eventName,ref,workflow,job,took
        env:
          # slack settings URL: https://yan-hubot-study.slack.com/services/8095672237655?updated=1
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
